using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectSpecificPrograms.TransCanadaUS
{
    public class TC_US_ExistingConditions_Layers
    {
        public const string AccessRoad = "Access Road";
        public const string AccessRoadLabel = "Access Road Label";
        public const string AerialMarkerPost = "Aerial Marker Post";
        public const string Alt_Route_1 = "Alt_Route_1";
        public const string Alt_Route_2 = "Alt_Route_2";
        public const string Alt_Route_3 = "Alt_Route_3";
        public const string Berm = "Berm";
        public const string CableLine = "Cable Line";
        public const string CatchBasinSymbol = "Catch Basin Symbol";
        public const string CathodicTest = "Cathodic Test";
        public const string CenterofRoad = "Center of Road";
        public const string Culvert = "Culvert";
        public const string DrainBarDitch = "Drain Bar Ditch";
        public const string DrillHoleSymbol = "Drill Hole Symbol";
        public const string E_Util_UPole_S = "E_Util_UPole_S";
        public const string EdgeofRoad = "Edge of Road";
        public const string ElecCable = "Elec Cable";
        public const string ElectricBoxSymbol = "Electric Box Symbol";
        public const string ElectricHandholeSymbol = "Electric Handhole Symbol";
        public const string ExistingTCPipeline = "Existing TC Pipeline";
        public const string FENCE = "FENCE";
        public const string FiberOpticLine = "Fiber Optic Line";
        public const string FireHydrantSymbol = "Fire Hydrant Symbol";
        public const string FlowLine = "Flow Line";
        public const string ForeignPipeline = "Foreign Pipeline";
        public const string GasValveSymbol = "Gas Valve Symbol";
        public const string GuardRail = "Guard Rail";
        public const string GuyWireAnchorSymbol = "Guy Wire & Anchor Symbol";
        public const string HFrameTowerSymbol = "H-Frame Tower Symbol";
        public const string House = "House";
        public const string InletSymbol = "InletSymbol";
        public const string InternationalBoundaryLine = "International BoundaryLine";
        public const string IronRodPinSymbol = "Iron Rod & Pin Symbol";
        public const string NaturalGround = "Natural Ground";
        public const string PNCTRL = "PNCTRL";
        public const string PNFENCE = "PNFENCE";
        public const string PNFPP = "PNFPP";
        public const string PNFPX = "PNFPX";
        public const string PNGRND = "PNGRND";
        public const string PNLAND = "PNLAND";
        public const string PNMISC = "PNMISC";
        public const string PNMON = "PNMON";
        public const string PNPIPE = "PNPIPE";
        public const string PNRD = "PNRD";
        public const string PNROUTE = "PNROUTE";
        public const string PNTOPO = "PNTOPO";
        public const string PNTS = "PNTS ";
        public const string PNUTIL = "PNUTIL";
        public const string PNWATER = "PNWATER";
        public const string PNWET = "PNWET";
        public const string POWERLINE = "POWER LINE";
        public const string PowerPoleSymbol = "Power Pole Symbol";
        public const string Railroad = "Railroad";
        public const string SanSewerManholeSymbol = "San Sewer Manhole Symbol";
        public const string SanitarySewer = "Sanitary Sewer";
        public const string SectionLines = "Section Lines";
        public const string SignSymbol = "Sign Symbol";
        public const string StoneConcreteMonumentSymbol = "Stone & Concrete MonumentSymbol";
        public const string StoneRockFence = "Stone & Rock Fence";
        public const string StormSewer = "Storm Sewer";
        public const string StormSewerManholeSymbol = "Storm Sewer Manhole Symbol";
        public const string Struct = "Struct";
        public const string TAP = "TAP";
        public const string TelephoneHandholeSymbol = "Telephone Handhole Symbol";
        public const string TelephoneLine = "Telephone Line";
        public const string TEXT = "TEXT";
        public const string TreeLine = "Tree Line";
        public const string TreeSymbol = "Tree Symbol";
        public const string TopofBerm = "Top of Berm";
        public const string ToeofBerm = "Toe of Berm";
        public const string TopofSlope = "Top of Slope";
        public const string ToeofSlope = "Toe of Slope";
        public const string Valve = "E_Fab_Valve";
        public const string ValveBoxSymbol = "Valve Box Symbol";
        public const string WaterLine = "Water Line";
        public const string WaterValveSymbol = "Water Valve Symbol";
        public const string WaterWell = "Water Well";
        public const string WellSymbol = "Well Symbol";
    }
}
